apiVersion: v1
kind: Pod
metadata: 
  name: multi-conatiner
spec:
  # list of containers
  containers: 
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "300"]  